/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./workers/share-analytics/wrangler.jsonc --include-runtime=false ./workers/share-analytics/worker-configuration.d.ts` (hash: 5541572d0c76bc9664c1295323cb8f69)
interface __BaseEnv_Env {
	DB: D1Database;
	SHARE_ANALYTICS_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
