/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./workers/share-analytics/wrangler.jsonc --include-runtime=false ./workers/share-analytics/worker-configuration.d.ts` (hash: 037a6961a7f9d0652ea34e49fdbf0653)
interface __BaseEnv_Env {
	DB: D1Database;
	SHARE_ANALYTICS_GLOBAL_RATE_LIMITER: RateLimit;
	SHARE_ANALYTICS_CLIENT_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
